# Generated by Django 4.1.2 on 2022-10-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0004_alter_userprofile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="noteapp.userprofile",
            ),
        ),
    ]
