# Generated by Django 4.1.2 on 2022-10-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0006_rename_category_note_kategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="kategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_category",
                to="noteapp.category",
            ),
        ),
    ]
