# Generated by Django 4.1.2 on 2022-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0007_alter_note_kategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
