# Generated by Django 4.1.2 on 2022-10-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0010_alter_note_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pics",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
