# Generated by Django 4.1.2 on 2022-10-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0012_alter_userprofile_profile_pics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pics",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
