# Generated by Django 4.1.2 on 2022-10-27 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0013_alter_userprofile_profile_pics"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="pdf",
            field=models.FileField(
                default=datetime.datetime(
                    2022, 10, 27, 17, 37, 0, 761145, tzinfo=datetime.timezone.utc
                ),
                upload_to="",
            ),
            preserve_default=False,
        ),
    ]
