# Generated by Django 4.1.2 on 2022-12-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0016_rename_kategory_note_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pics",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
